name: airopedia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^2.0.0

  cloud_firestore: ^3.2.1
  firebase_auth: ^3.4.1
  google_sign_in: ^5.4.0

  shared_preferences: ^2.0.15

  #awesome_snackbar_content: ^0.0.5

  flutter_google_places: ^0.3.0
  google_place: ^0.4.7

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  auto_size_text: ^3.0.0 

  email_validator: ^2.0.1

  provider: ^6.0.3

  sqflite: ^2.0.3

  flutter_html: ^2.2.1

  intl: ^0.17.0

  html_unescape: ^2.0.0

  geolocator: ^7.6.2

  connectivity_plus: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_native_splash: ^2.0.5
  flutter_lints: ^1.0.4

flutter_native_splash: 
  color: "#0D67B5"
  image: assets\images\Airopedia-logos.png
  android: true
  ios: true

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/FrenchFlag.png
    - assets/images/GBFlag.png
    - assets/images/GermanFlag.png
    - assets/images/GreekFlag.png
    - assets/images/ItalianFlag.png
    - assets/images/PolishFlag.png
    - assets/images/PortugueseFlag.png
    - assets/images/RussianFlag.png
    - assets/images/SpainFlag.png
    - assets/images/UkranianFlag.png
    - assets/images/NoConnection.png

  fonts:
    - family: HVD_Comic_Serif_Pro
      fonts:
        - asset: assets/fonts/hvd_comic_serif_pro/HVD_Comic_Serif_Pro.otf

 