name: airopedia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^2.0.0


  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  auto_size_text: ^3.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_native_splash: ^2.0.5
  flutter_lints: ^1.0.4

flutter_native_splash: 
  color: "#0D67B5"
  image: assets\images\Airopedia-logos.png
  android: true
  ios: true

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  fonts:
    - family: HVD_Comic_Serif_Pro
      fonts:
        - asset: assets/fonts/hvd_comic_serif_pro/HVD_Comic_Serif_Pro.otf

 